// AUTO-GENERATED FILE
// DO NOT EDIT BY HAND
// Generated by: node scripts/create-migration.js <name>

import type { Migration } from './types'
import { m20260106121718_init } from './20260106121718_init'
import { m20260106123754_create_accounts } from './20260106123754_create_accounts'
import { m20260106123802_create_categories } from './20260106123802_create_categories'
import { m20260106123806_create_transactions } from './20260106123806_create_transactions'
import { m20260112131153_add_system_columns } from './20260112131153_add_system_columns'
import { m20260114121532_create_seed_runs } from './20260114121532_create_seed_runs'

export const MIGRATIONS: Migration[] = [
  m20260106121718_init,
  m20260106123754_create_accounts,
  m20260106123802_create_categories,
  m20260106123806_create_transactions,
  m20260112131153_add_system_columns,
  m20260114121532_create_seed_runs
]
